<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <ApplicationIcon>../../assets/WinAirPlay.ico</ApplicationIcon>
        <Version>2.0.0</Version>
        <Product>WinAirPlay</Product>
        <Description>Stream Windows audio to AirPlay speakers.</Description>
        <Copyright>Copyright (c) 2026 Timo</Copyright>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../WinAirPlay.Core/WinAirPlay.Core.csproj" />
        <Content Include="../../native/bin/winairplay_audio.dll" Link="winairplay_audio.dll" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
